-- V1: baseline schema, generated by Hibernate 6.4 (PostgreSQLDialect) from the JPA
-- entities on 2026-07-02. Existing databases are baselined past this file
-- (spring.flyway.baseline-on-migrate=true, baseline-version=1); fresh databases
-- get the full schema here. ddl-auto stays 'validate' — Flyway owns the schema. (AUDIT P0-3)

create table sudoku_boards (chaos_mode boolean not null, cosmic_drip_level integer not null, cosmic_events integer not null, cosmic_mode boolean not null, diagonal_rules boolean not null, difficulty integer not null, hint_count integer not null, infinite_mode boolean not null, lives integer not null, max_lives integer not null, mirror_mode boolean not null, move_count integer not null, revives integer not null, score integer not null, size integer not null, solved boolean not null, tens_rule boolean not null, time_attack boolean not null, used_undo boolean not null, id bigserial not null, solve_time_seconds bigint not null, start_time timestamp(6), time_limit_seconds bigint not null, game_id varchar(255), player_id varchar(255), primary key (id));

create table user_achievements (achievements boolean, user_id bigint not null, achievements_key varchar(255) not null, primary key (user_id, achievements_key));

create table user_friends (friends bigint, user_id bigint not null);

create table user_match_history (match_won boolean, match_timestamp timestamp(6), user_id bigint not null);

create table user_power_ups (power_ups integer, user_id bigint not null, power_ups_key varchar(255) not null, primary key (user_id, power_ups_key));

create table users (cosmic_drip integer not null check (cosmic_drip>=0), duel_losses integer not null check (duel_losses>=0), duel_wins integer not null check (duel_wins>=0), fan_count integer not null check (fan_count>=0), gems integer not null check (gems>=0), hype_meter integer not null check (hype_meter>=0), level integer not null check (level>=1), points integer not null check (points>=0), streak integer not null check (streak>=0), xp integer not null check (xp>=0), id bigint not null, last_login timestamp(6) not null, avatar_url varchar(255), last_login_ip varchar(255), platform varchar(255), theme_preference varchar(255), username varchar(255), primary key (id));

alter table if exists user_achievements add constraint FK6vt5fpu0uta41vny1x6vpk45k foreign key (user_id) references users;

alter table if exists user_friends add constraint FKk08ugelrh9cea1oew3hgxryw2 foreign key (user_id) references users;

alter table if exists user_match_history add constraint FKt42t713kg4lo0dv79pjc0plxq foreign key (user_id) references users;

alter table if exists user_power_ups add constraint FK7lc6bfvni2a7utkqctvlqmx2h foreign key (user_id) references users;
