package com.xai.sudokupro.db;

import com.xai.sudokupro.model.SudokuBoard;
import com.xai.sudokupro.model.User;
import com.xai.sudokupro.support.ExternalServices;
import org.flywaydb.core.Flyway;
import org.flywaydb.core.api.output.MigrateResult;
import org.hibernate.boot.Metadata;
import org.hibernate.boot.MetadataSources;
import org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy;
import org.hibernate.boot.registry.StandardServiceRegistry;
import org.hibernate.boot.registry.StandardServiceRegistryBuilder;
import org.hibernate.cfg.AvailableSettings;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy;

import java.io.InputStream;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.Properties;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Runs the real Flyway V1-V9 chain against a real PostgreSQL server, in every
 * environment: a developer machine, this container, and CI.
 *
 * <p><b>What changed and why.</b> This class used to be
 * {@code @Testcontainers(disabledWithoutDocker = true)}. Anywhere Docker was absent it
 * disabled itself with no signal at all: two green-looking tests that never executed a
 * single migration. The migration chain — nine files that decide whether the application
 * can start against a real database — was therefore completely unverified, and three
 * genuine defects survived in it (see V3/V4/V9). Connection details now come from
 * configuration ({@link ExternalServices}) with localhost defaults, and an unreachable
 * PostgreSQL FAILS the test with an explanatory message instead of skipping.
 *
 * <p><b>H2 cannot substitute.</b> The chain is PostgreSQL-specific: a PL/pgSQL {@code DO}
 * block (V2), {@code ADD GENERATED BY DEFAULT AS IDENTITY} (V4), partial unique indexes
 * (V8/V9) and a window-function dedupe. Only a real server exercises them.
 *
 * <p>Each test migrates its OWN freshly created, uniquely named database and drops it
 * afterwards, so runs never touch an existing database and can run concurrently.
 *
 * <p>The three scenarios are the three shapes a real deployment can be in:
 * <ol>
 *   <li><b>Fresh</b> — empty database, V1 builds the schema and V2-V9 follow.</li>
 *   <li><b>Legacy pre-Flyway</b> — a hand-made schema from before Flyway existed, with
 *       {@code start_time} still BIGINT and no {@code users} table at all (the server
 *       ran games only). Baselined past V1; V2+ must upgrade it.</li>
 *   <li><b>Hibernate-managed (the dev profile)</b> — {@code application-dev.properties}
 *       sets {@code ddl-auto=update} and {@code spring.flyway.enabled=false}, so a dev or
 *       staging database has a schema Hibernate built and a Flyway history that has NOT
 *       kept up with it. Adopting Flyway there must not blow up. This scenario is what a
 *       promotion from dev to prod actually looks like, and it is where two of the three
 *       migration defects lived.</li>
 * </ol>
 */
class FlywayMigrationTest {

    /** Production Flyway settings, read from application.properties so the test cannot drift from it. */
    private static String[] locations;
    private static boolean baselineOnMigrate;
    private static String baselineVersion;

    private static final List<String> scratchDatabases = new ArrayList<>();

    @BeforeAll
    static void requireRealPostgres() throws Exception {
        ExternalServices.requirePostgres();

        Properties app = new Properties();
        try (InputStream in = FlywayMigrationTest.class.getResourceAsStream("/application.properties")) {
            assertNotNull(in, "application.properties must be on the test classpath");
            app.load(in);
        }
        String configured = app.getProperty("spring.flyway.locations");
        assertNotNull(configured, "spring.flyway.locations must be configured in application.properties");
        // {vendor} is resolved by Boot from the JDBC url; this test always targets PostgreSQL.
        locations = configured.replace("{vendor}", "postgresql").split("\\s*,\\s*");
        baselineOnMigrate = Boolean.parseBoolean(app.getProperty("spring.flyway.baseline-on-migrate", "false"));
        baselineVersion = app.getProperty("spring.flyway.baseline-version", "1");

        assertTrue(baselineOnMigrate,
            "these scenarios encode baseline-on-migrate=true; application.properties disagrees");
    }

    @AfterAll
    static void dropScratchDatabases() {
        for (String db : scratchDatabases) {
            try (Connection admin = ExternalServices.connect(ExternalServices.dbAdminDatabase());
                 Statement st = admin.createStatement()) {
                st.execute("DROP DATABASE IF EXISTS " + db + " WITH (FORCE)");
            } catch (Exception e) {
                System.err.println("WARNING: could not drop scratch database " + db + ": " + e);
            }
        }
    }

    // ------------------------------------------------------------------
    // Scenario 1: a fresh, empty database
    // ------------------------------------------------------------------

    @Test
    void freshDatabaseGetsFullSchema() throws Exception {
        String db = createScratchDatabase("fresh");

        MigrateResult result = migrate(db);
        assertTrue(result.success, "Migration chain must apply cleanly on a fresh database");
        // Counted from the migration files rather than hard-coded. A literal here was wrong
        // within hours of being written: a parallel change added V10 and this assertion
        // failed with "expected: <9> but was: <10>" — a green-to-red on work that was
        // perfectly correct. The invariant worth pinning is "every migration on disk ran",
        // not "there are exactly N of them".
        int onDisk = countMigrationFiles();
        assertEquals(onDisk, result.migrationsExecuted,
            "every migration file must run on a fresh database — found " + onDisk
                + " on the classpath (executed: " + result.migrations + ")");

        try (Connection c = ExternalServices.connect(db)) {
            for (String table : new String[]{"sudoku_boards", "users", "user_achievements",
                                             "user_friends", "user_match_history", "user_power_ups"}) {
                assertTrue(tableExists(c, table), "V1 must create table " + table);
            }
            // start_time is TIMESTAMP from day one on fresh installs
            assertEquals("timestamp without time zone", columnType(c, "sudoku_boards", "start_time"));
            // cells_json (save/load grid snapshot) exists on fresh installs
            assertEquals("text", columnType(c, "sudoku_boards", "cells_json"));
            for (String version : new String[]{"1", "2", "3", "4", "5", "6", "7", "8", "9"}) {
                assertTrue(migrationApplied(c, version), "V" + version + " must be recorded as applied");
            }
            assertEquals("integer", columnType(c, "users", "duel_rating"), "V5 adds duel_rating");
            assertEquals("character varying", columnType(c, "users", "password_hash"), "V6 adds password_hash");
            assertEquals("boolean", columnType(c, "sudoku_boards", "rewards_granted"),
                "V7 adds rewards_granted (idempotent completion payouts)");

            // V8's whole point: a second row with the same game_id must be impossible.
            try (Statement st = c.createStatement()) {
                st.execute(insertBoard("dup-guard", "p1"));
                assertThrows(SQLException.class, () -> st.execute(insertBoard("dup-guard", "p2")),
                    "a duplicate game_id must be rejected — two rows permanently break findByGameId");
                // ... but a NULL game_id must still be allowed more than once (partial index).
                st.execute(insertBoard(null, "p3"));
                st.execute(insertBoard(null, "p4"));
                assertEquals(2, count(c, "select count(*) from sudoku_boards where game_id is null"),
                    "V8's index is partial: legacy NULL game_ids must not collide with each other");
            }

            // V9's whole point: a second row with the same username must be impossible.
            try (Statement st = c.createStatement()) {
                st.execute(insertUser("dupname"));
                assertThrows(SQLException.class, () -> st.execute(insertUser("dupname")),
                    "a duplicate username must be rejected — two rows permanently break findByUsername");
            }

            // V4: users.id is generated — inserting without an id must work, above the legacy range.
            try (Statement st = c.createStatement()) {
                st.execute(insertUser("idtest"));
                try (ResultSet rs = st.executeQuery("SELECT id FROM users WHERE username='idtest'")) {
                    assertTrue(rs.next());
                    assertTrue(rs.getLong(1) >= 1_000_000_000L,
                        "generated ids must start above the legacy manual range");
                }
            }
        }

        // Re-running the chain against an already-migrated database is a clean no-op:
        // no repeated DDL, and no checksum/ordering complaint from validate-on-migrate.
        MigrateResult again = migrate(db);
        assertTrue(again.success, "a second migrate() on an up-to-date database must succeed");
        assertEquals(0, again.migrationsExecuted,
            "a second migrate() must execute nothing (executed: " + again.migrations + ")");
    }

    /**
     * The production runtime sets {@code ddl-auto=validate}: if the schema the migrations
     * build does not match the JPA entities, every pod fails to start. Nothing else in the
     * suite compares the two — the H2 test profile builds its schema FROM the entities, so
     * it agrees with them by construction and can never detect this drift.
     */
    @Test
    void migratedSchemaSatisfiesHibernateValidate() throws Exception {
        String db = createScratchDatabase("validate");
        assertTrue(migrate(db).success);

        assertDoesNotThrow(() -> runHibernateSchemaAction(db, "validate"),
            "the Flyway-built schema must satisfy Hibernate ddl-auto=validate — production "
                + "runs with validate and every pod refuses to start otherwise");
    }

    // ------------------------------------------------------------------
    // Scenario 2: a legacy pre-Flyway database
    // ------------------------------------------------------------------

    @Test
    void legacyDatabaseIsBaselinedAndStartTimeConverted() throws Exception {
        String db = createScratchDatabase("legacy");

        // Minimal legacy shape: the pre-Flyway era left start_time as BIGINT (epoch millis),
        // and installs that only ran games never created a users table at all — the case
        // V4's own comment promises still "migrates cleanly".
        try (Connection c = ExternalServices.connect(db); Statement st = c.createStatement()) {
            st.execute("CREATE TABLE sudoku_boards (id bigserial primary key, game_id varchar(255), "
                + "start_time bigint)");
            st.execute("INSERT INTO sudoku_boards (game_id, start_time) VALUES ('g1', 1719900000000)");
        }

        MigrateResult result = migrate(db);
        assertTrue(result.success, "the chain must upgrade a legacy pre-Flyway database");

        try (Connection c = ExternalServices.connect(db)) {
            // Baselined past V1 (schema pre-exists), V2+ applied.
            assertFalse(migrationApplied(c, "1"), "V1 must be skipped on a baselined legacy database");
            for (String version : new String[]{"2", "3", "4", "5", "6", "7", "8", "9"}) {
                assertTrue(migrationApplied(c, version),
                    "V" + version + " must apply on a legacy database with no users table");
            }
            assertEquals("text", columnType(c, "sudoku_boards", "cells_json"),
                "V3 must add cells_json to upgraded legacy databases");
            assertEquals("boolean", columnType(c, "sudoku_boards", "rewards_granted"),
                "V7 must add rewards_granted to upgraded legacy databases");
            assertTrue(indexExists(c, "ux_sudoku_boards_game_id"), "V8 must create the game_id index");
            assertFalse(tableExists(c, "users"),
                "V4/V5/V6/V9 must no-op on, not invent, a users table this install never had");

            // The BIGINT column is now a real timestamp, data converted not lost.
            assertEquals("timestamp without time zone", columnType(c, "sudoku_boards", "start_time"));
            try (Statement st = c.createStatement();
                 ResultSet rs = st.executeQuery(
                     "SELECT extract(year FROM start_time) FROM sudoku_boards WHERE game_id='g1'")) {
                assertTrue(rs.next());
                assertEquals(2024, (int) rs.getDouble(1), "Epoch-millis value must convert to the same instant");
            }
        }
    }

    // ------------------------------------------------------------------
    // Scenario 3: a database Hibernate built (the dev profile), adopting Flyway
    // ------------------------------------------------------------------

    /**
     * The dev profile disables Flyway and lets Hibernate own the schema
     * ({@code ddl-auto=update}), so a dev/staging database drifts ahead of its Flyway
     * history: columns that a migration is supposed to add are already there, and
     * {@code users.id} is already database-generated because the entity is
     * {@code @GeneratedValue(IDENTITY)}. Promoting such a database to the Flyway-managed
     * configuration must still work.
     *
     * <p>The starting schema here is produced by Hibernate itself from the real entities —
     * the same generator {@code ddl-auto} uses — rather than being hand-written, so it
     * cannot quietly diverge from what dev actually creates.
     */
    @Test
    void hibernateManagedDevDatabaseCanAdoptFlyway() throws Exception {
        String db = createScratchDatabase("devadopt");

        // ddl-auto, run by Hibernate itself against the real entities — the dev profile's schema.
        runHibernateSchemaAction(db, "create");

        // Pre-existing gameplay data, as any dev/staging database would have.
        try (Connection c = ExternalServices.connect(db); Statement st = c.createStatement()) {
            st.execute(insertBoard("dev-game", "devplayer"));
            st.execute(insertUser("devplayer"));
            assertTrue(idIsDatabaseGenerated(c),
                "precondition: @GeneratedValue(IDENTITY) leaves users.id database-generated, which is "
                    + "exactly what V4 would otherwise try (and fail) to add");
        }

        MigrateResult result = migrate(db);
        assertTrue(result.success,
            "the chain must apply to a database Hibernate already built (dev -> prod promotion)");

        try (Connection c = ExternalServices.connect(db)) {
            assertFalse(migrationApplied(c, "1"), "V1 must be baselined away on a pre-existing schema");
            for (String version : new String[]{"2", "3", "4", "5", "6", "7", "8", "9"}) {
                assertTrue(migrationApplied(c, version),
                    "V" + version + " must apply to a Hibernate-managed database");
            }
            // Data survived, and the constraints the chain exists to add are now enforced.
            assertEquals(1, count(c, "select count(*) from sudoku_boards where game_id='dev-game'"),
                "existing rows must survive the migration");
            assertEquals(1, count(c, "select count(*) from users where username='devplayer'"));
            assertTrue(indexExists(c, "ux_sudoku_boards_game_id"), "V8 must create the game_id index");
            assertTrue(indexExists(c, "ux_users_username"), "V9 must create the username index");
            try (Statement st = c.createStatement()) {
                assertThrows(SQLException.class, () -> st.execute(insertBoard("dev-game", "other")),
                    "V8's uniqueness must be enforced after a dev-profile adoption too");
                assertThrows(SQLException.class, () -> st.execute(insertUser("devplayer")),
                    "V9's uniqueness must be enforced after a dev-profile adoption too");
            }
            // users.id stays generated — inserting without an id must still work.
            try (Statement st = c.createStatement()) {
                st.execute(insertUser("devplayer2"));
                assertEquals(1, count(c, "select count(*) from users where username='devplayer2'"));
            }
        }
    }

    /**
     * The other shape a database-generated {@code users.id} takes: a true IDENTITY column
     * ({@code GENERATED BY DEFAULT AS IDENTITY}), which is what newer Hibernate versions and
     * hand-written DDL produce. V4 must step over it — {@code ADD GENERATED} has no
     * {@code IF NOT EXISTS} form and errors with "column id ... is already an identity column",
     * which failed the whole chain.
     */
    @Test
    void usersTableThatAlreadyHasAnIdentityIdCanAdoptFlyway() throws Exception {
        String db = createScratchDatabase("identity");

        try (Connection c = ExternalServices.connect(db); Statement st = c.createStatement()) {
            st.execute("CREATE TABLE sudoku_boards (id bigserial primary key, game_id varchar(255), "
                + "start_time timestamp)");
            st.execute("CREATE TABLE users (id bigint generated by default as identity primary key, "
                + "username varchar(255), points integer not null default 0, "
                + "gems integer not null default 0, xp integer not null default 0)");
            st.execute("INSERT INTO users (username) VALUES ('already-identity')");
        }

        assertTrue(migrate(db).success,
            "the chain must step over a users.id that is already an identity column");

        try (Connection c = ExternalServices.connect(db)) {
            assertTrue(migrationApplied(c, "4"), "V4 must be recorded, having found nothing to do");
            assertTrue(idIsDatabaseGenerated(c), "users.id must still be database-generated");
            assertTrue(indexExists(c, "ux_users_username"), "V9 must still add the username index");
            try (Statement st = c.createStatement()) {
                st.execute("INSERT INTO users (username) VALUES ('second')");
                assertEquals(2, count(c, "select count(*) from users"),
                    "inserting without an id must still work after V4");
            }
        }
    }

    /** V8/V9 dedupe before constraining; a database that already holds duplicates must be repaired, not rejected. */
    @Test
    void duplicateRowsAreDedupedBeforeTheUniqueIndexesAreAdded() throws Exception {
        String db = createScratchDatabase("dupes");

        // A pre-V8/V9 schema that lets the duplicates the migrations exist to clean up actually exist.
        try (Connection c = ExternalServices.connect(db); Statement st = c.createStatement()) {
            st.execute("CREATE TABLE sudoku_boards (id bigserial primary key, game_id varchar(255), "
                + "start_time timestamp, cells_json text)");
            st.execute("INSERT INTO sudoku_boards (game_id, start_time, cells_json) VALUES "
                + "('race', timestamp '2026-01-01 00:00:00', null), "
                + "('race', timestamp '2026-01-01 00:00:00', '{\"cells\":1}')");
            st.execute("CREATE TABLE users (id bigserial primary key, username varchar(255), "
                + "points integer not null default 0, gems integer not null default 0, "
                + "xp integer not null default 0)");
            st.execute("INSERT INTO users (username, points, gems, xp) VALUES "
                + "('racer', 0, 0, 0), ('racer', 5, 5, 5)");
        }

        assertTrue(migrate(db).success, "the chain must repair duplicates rather than fail on them");

        try (Connection c = ExternalServices.connect(db)) {
            assertEquals(1, count(c, "select count(*) from sudoku_boards where game_id='race'"),
                "V8 must collapse duplicate game_id rows to one");
            assertEquals(1, count(c, "select count(*) from sudoku_boards where cells_json is not null"),
                "V8 must keep the row that actually carries a grid snapshot");
            assertEquals(1, count(c, "select count(*) from users where username='racer'"),
                "V9 must collapse duplicate username rows to one");
            assertEquals(5, count(c, "select points from users where username='racer'"),
                "V9 must keep the row carrying the most progress");
        }
    }

    // ---- helpers ----

    private static MigrateResult migrate(String database) {
        return Flyway.configure()
            .dataSource(ExternalServices.jdbcUrl(database), ExternalServices.dbUser(),
                ExternalServices.dbPassword())
            .locations(locations)
            .baselineOnMigrate(baselineOnMigrate)
            .baselineVersion(baselineVersion)
            .load()
            .migrate();
    }

    /**
     * How many migration files the production configuration will actually pick up.
     *
     * <p>Resolved from the same {@code spring.flyway.locations} the app uses, so adding a
     * migration keeps this test honest instead of breaking it, and *removing* one from the
     * classpath still fails the assertion it feeds.
     */
    private static int countMigrationFiles() throws Exception {
        int total = 0;
        for (String location : locations) {
            String path = location.replace("classpath:", "").trim();
            java.net.URL dir = FlywayMigrationTest.class.getClassLoader().getResource(path);
            assertNotNull(dir, "migration location not on the classpath: " + location);
            try (var files = java.nio.file.Files.list(java.nio.file.Paths.get(dir.toURI()))) {
                total += (int) files.filter(f -> f.getFileName().toString().endsWith(".sql")).count();
            }
        }
        assertTrue(total > 0, "no migration files found under " + String.join(", ", locations));
        return total;
    }

    /** Creates a uniquely named empty database, registered for teardown. */
    private static String createScratchDatabase(String label) throws Exception {
        String name = ("flyway_it_" + label + "_"
            + UUID.randomUUID().toString().replace("-", "").substring(0, 10)).toLowerCase(Locale.ROOT);
        try (Connection admin = ExternalServices.connect(ExternalServices.dbAdminDatabase());
             Statement st = admin.createStatement()) {
            st.execute("CREATE DATABASE " + name);
        }
        scratchDatabases.add(name);
        return name;
    }

    /**
     * Runs a Hibernate {@code ddl-auto} action ("create", "validate", ...) against {@code database}
     * using the real entity classes and the production dialect. Building the SessionFactory is what
     * performs the action, exactly as it does inside a booting application.
     */
    private static void runHibernateSchemaAction(String database, String ddlAuto) {
        StandardServiceRegistry registry = hibernateRegistry(database, ddlAuto);
        try {
            entityMetadata(registry).buildSessionFactory().close();
        } finally {
            StandardServiceRegistryBuilder.destroy(registry);
        }
    }

    private static StandardServiceRegistry hibernateRegistry(String database, String ddlAuto) {
        return new StandardServiceRegistryBuilder()
            .applySetting("hibernate.connection.driver_class", "org.postgresql.Driver")
            .applySetting("hibernate.connection.url", ExternalServices.jdbcUrl(database))
            .applySetting("hibernate.connection.username", ExternalServices.dbUser())
            .applySetting("hibernate.connection.password", ExternalServices.dbPassword())
            // The production dialect, from application.properties' spring.jpa.database-platform.
            .applySetting("hibernate.dialect", "org.hibernate.dialect.PostgreSQLDialect")
            // Spring Boot's defaults, which decide that `gameId` maps to the column `game_id`.
            // Raw Hibernate would use `gameId`, so without these the schema this test builds
            // and validates would not be the schema the application actually uses.
            .applySetting(AvailableSettings.PHYSICAL_NAMING_STRATEGY,
                CamelCaseToUnderscoresNamingStrategy.class.getName())
            .applySetting(AvailableSettings.IMPLICIT_NAMING_STRATEGY,
                SpringImplicitNamingStrategy.class.getName())
            .applySetting("hibernate.hbm2ddl.auto", ddlAuto)
            .applySetting("hibernate.show_sql", "false")
            .build();
    }

    private static Metadata entityMetadata(StandardServiceRegistry registry) {
        return new MetadataSources(registry)
            .addAnnotatedClass(SudokuBoard.class)
            .addAnnotatedClass(User.class)
            .buildMetadata();
    }

    private static String insertBoard(String gameId, String playerId) {
        return "INSERT INTO sudoku_boards (game_id, player_id, chaos_mode, cosmic_drip_level, "
            + "cosmic_events, cosmic_mode, diagonal_rules, difficulty, hint_count, infinite_mode, "
            + "lives, max_lives, mirror_mode, move_count, revives, score, size, solved, tens_rule, "
            + "time_attack, used_undo, solve_time_seconds, time_limit_seconds) VALUES ("
            + (gameId == null ? "null" : "'" + gameId + "'") + ",'" + playerId
            + "',false,0,0,false,false,1,0,false,3,3,false,0,0,0,9,false,false,false,false,0,0)";
    }

    /**
     * Every NOT NULL column is supplied explicitly: the Flyway schema gives duel_rating a
     * DEFAULT and the Hibernate-built one does not, and this insert has to work on both.
     */
    private static String insertUser(String username) {
        return "INSERT INTO users (username, points, streak, duel_wins, duel_losses, gems, "
            + "level, xp, fan_count, hype_meter, cosmic_drip, duel_rating, last_login) "
            + "VALUES ('" + username + "', 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1000, now())";
    }

    private static boolean tableExists(Connection c, String table) throws Exception {
        try (Statement st = c.createStatement();
             ResultSet rs = st.executeQuery(
                 "SELECT 1 FROM information_schema.tables WHERE table_name = '" + table + "'")) {
            return rs.next();
        }
    }

    private static boolean indexExists(Connection c, String index) throws Exception {
        try (Statement st = c.createStatement();
             ResultSet rs = st.executeQuery(
                 "SELECT 1 FROM pg_indexes WHERE indexname = '" + index + "'")) {
            return rs.next();
        }
    }

    /**
     * True when the database itself supplies users.id — either as an IDENTITY column or via a
     * sequence default (bigserial). Both shapes exist in the wild and both are ones V4 must
     * step over rather than try to convert.
     */
    private static boolean idIsDatabaseGenerated(Connection c) throws Exception {
        try (Statement st = c.createStatement();
             ResultSet rs = st.executeQuery("SELECT is_identity, column_default "
                 + "FROM information_schema.columns WHERE table_name = 'users' AND column_name = 'id'")) {
            assertTrue(rs.next(), "users.id must exist");
            return "YES".equals(rs.getString(1)) || rs.getString(2) != null;
        }
    }

    private static long count(Connection c, String sql) throws Exception {
        try (Statement st = c.createStatement(); ResultSet rs = st.executeQuery(sql)) {
            assertTrue(rs.next());
            return rs.getLong(1);
        }
    }

    private static String columnType(Connection c, String table, String column) throws Exception {
        try (Statement st = c.createStatement();
             ResultSet rs = st.executeQuery(
                 "SELECT data_type FROM information_schema.columns WHERE table_name = '"
                 + table + "' AND column_name = '" + column + "'")) {
            assertTrue(rs.next(), "column " + table + "." + column + " must exist");
            return rs.getString(1);
        }
    }

    private static boolean migrationApplied(Connection c, String version) throws Exception {
        try (Statement st = c.createStatement();
             ResultSet rs = st.executeQuery(
                 "SELECT 1 FROM flyway_schema_history WHERE version = '" + version
                 + "' AND type NOT IN ('BASELINE') AND success")) {
            return rs.next();
        }
    }
}
