-- V4: users.id becomes database-generated (identity). Until now every User row
-- needed a manually assigned id, which made auto-provisioning player wallets
-- (hint economy / duel records) impossible. GENERATED BY DEFAULT keeps any
-- legacy manual inserts working; the start value is far above hand-assigned
-- ids so the sequence can never collide with them.
--
-- Guarded (2026-07-26, with FlywayMigrationTest). The previous one-liner was
--     alter table if exists users alter column id add generated by default as identity (...)
-- whose only guard was on the TABLE. ADD GENERATED has no IF NOT EXISTS form, so the
-- migration failed hard on every database where users.id was already generated:
--
--   * users.id is already an identity column
--     'ERROR: column "id" of relation "users" is already an identity column'
--     This is what Hibernate produces from User's @GeneratedValue(IDENTITY), so it is
--     the state of every dev/staging database — application-dev.properties disables
--     Flyway and runs ddl-auto=update. Adopting Flyway there was impossible.
--
--   * users.id already has a serial default (nextval)
--     'ERROR: column "id" of relation "users" already has a default value'
--     This is the state of the shared development database in this environment, whose
--     Flyway history stops at V2 while Hibernate kept evolving the schema past it.
--
-- Both of those columns are already database-generated, which is the entire point of
-- this migration, so the correct action is to leave them alone rather than abort the
-- whole chain. Only a plain, defaultless bigint column — what V1 creates on a fresh
-- install — is converted.
--
-- OPERATORS: this edit changes the file's Flyway checksum. A database that already
-- applied the previous version of V4 must be repaired once (`flyway repair`) before
-- its next migrate, or validate-on-migrate will refuse to run.

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = current_schema() AND table_name = 'users' AND column_name = 'id'
    ) THEN
        -- Pre-Flyway installs that never created a users table (server ran games only).
        RAISE NOTICE 'users.id does not exist - nothing to convert.';

    ELSIF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = current_schema() AND table_name = 'users' AND column_name = 'id'
          AND is_identity = 'YES'
    ) THEN
        RAISE NOTICE 'users.id is already an identity column - nothing to convert.';

    ELSIF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = current_schema() AND table_name = 'users' AND column_name = 'id'
          AND column_default IS NOT NULL
    ) THEN
        -- bigserial and friends: already generated by a sequence, so ids are handed out
        -- without the caller supplying one. Converting would orphan the existing sequence
        -- for no behavioural gain.
        RAISE NOTICE 'users.id already has a generated default - leaving it as it is.';

    ELSE
        ALTER TABLE users
            ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (START WITH 1000000000);
        RAISE NOTICE 'users.id is now GENERATED BY DEFAULT AS IDENTITY.';
    END IF;
END
$$;
