-- V4: users.id becomes database-generated (identity). Until now every User row
-- needed a manually assigned id, which made auto-provisioning player wallets
-- (hint economy / duel records) impossible. GENERATED BY DEFAULT keeps any
-- legacy manual inserts working; the start value is far above hand-assigned
-- ids so the sequence can never collide with them.
-- IF EXISTS: pre-Flyway installs that never created the users table (server ran
-- games only) still migrate cleanly; the table then comes from a later baseline.
alter table if exists users alter column id add generated by default as identity (start with 1000000000);
